spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 55b70678fe1505923573
            clientSecret: 578e1e60cf18939f13512230e218ce7648963023
            scope: user